export function Methodology() {
  return <section id="methodology" className="methodology-section">
    <div className="section-heading"><div><p className="overline">A WORKING DEFINITION</p><h2>什么发生了变化，<br/>谁在改进下一代？</h2></div><span className="section-index">01 / METHODOLOGY</span></div>
    <div className="definition-card"><span className="overline">RECURSIVE SELF-IMPROVEMENT</span><p>在明确的 <strong>System Boundary</strong> 内，系统利用 Feedback，持续修改承担后续改进功能的组件；修改后的组件再次参与生成学习经验、提出、评价、选择或整合后续版本。</p><p className="definition-footnote">这是本站用于整理文献的 Operational Definition。不同论文对 RSI 的范围仍有分歧；本定义区分机制成立与效果成立，不预设无限进步、加速增长或 ASI。</p></div>
    <div className="method-grid"><article><span className="method-index">01</span><h3>Persistent Update</h3><p>先确认更新能否进入后续 Attempts、Tasks 或 Improvement Rounds。一次回答的改写、只读检索和临时 Context 变化，需要与持久系统更新分开。</p></article><article><span className="method-index">02</span><h3>Recursive Mechanism</h3><p>追踪被更新组件在下一轮的功能。Weights、Prompt、Memory 与 Code 都可能承担 Improver；修改代码或重复循环本身不足以证明 Recursive Reuse。Model 生成下一轮训练数据可形成结构性反馈；这不代表训练算法本身被改写。</p></article><article><span className="method-index">03</span><h3>Demonstrated Recursive Gain</h3><p>进一步检验更新后的 Improver 是否更善于产生有效的后继版本。固定起始 Solver、候选预算和 Evaluator，比较后继质量，比只看最终 Task Score 更有辨识力。</p></article></div>
    <div className="axis-methods"><div><h3>Evolution Target</h3><p>五个可重叠主题：Model、Prompt &amp; Context、Memory、Tool &amp; Skill、Architecture。它们回答“改了什么”。没有持久更新的工作仍可从 All Papers 找到。</p></div><div><h3>Paper Type</h3><p>Method、Survey、Theory、Benchmark、Empirical Analysis 独立标注。Survey 讨论 Model Evolution，不等于该 Survey 训练了一个会自我改进的 Model。</p></div><div><h3>Loop Role</h3><p>Solver、Experience Generator、Evaluator、Proposer、Selector、Integrator 回答“变化影响了循环中的什么功能”。同一组件可以有多个 Role。</p></div><div><h3>Persistence &amp; Evidence</h3><p>记录更新保留范围、Recursive Reuse，以及 Task Gain、Transfer、Improver Quality Gain、Controlled Successor Gain 等证据。Evidence 是观察类型，不是统一能力阶梯。</p></div></div>
    <div className="taxonomy-cases"><h3>用边界案例检查分类</h3><dl><div><dt>Self-Refine</dt><dd>修改当前任务的回答，通常属于 Ephemeral Refinement；该循环本身没有证明跨任务的系统更新。</dd></div><div><dt>STaR · Self-Rewarding</dt><dd>更新后的 Model 分别重返 Experience Generator 与 Evaluator。两者都有 Recursive Reuse；Self-Rewarding 还测量了 Judge Quality，但这仍需与受控的后继增益区分。</dd></div><div><dt>TextGrad</dt><dd>Instance Optimization 与可复用 Prompt Optimization 分开记为 Variant。不能把前者的 Persistence 和后者的 Evidence 拼成一个虚构实验。</dd></div><div><dt>DGM · HyperAgents</dt><dd>检查哪些 Agent 组件实际被改写、哪些外层规则保持固定。局部 Recursive Mechanism 可以成立，开放式能力增长仍需额外证据。</dd></div></dl></div>
    <p className="classification-note">每个 Variant 记录 System Boundary、Feedback、更新角色和 Evidence Scope。保留固定 Base Model、测试集或人工 Gate 不会自动否定局部 Recursion；扩大边界也不能代替实际的更新证据。分类是基于原文的 Editorial Assessment，可随新证据修订。</p>
    <p className="methodology-sources">Primary Sources：<a href="https://arxiv.org/abs/2507.21046v4">A Survey of Self-Evolving Agents</a> · <a href="https://arxiv.org/abs/2607.13104v1">Self-Improvements in Modern Agentic Systems</a> · <a href="https://arxiv.org/abs/2603.19461v1">HyperAgents</a> · <a href="https://arxiv.org/abs/2609.11873v1">The Last AI Built by Humans</a>。以上文献提供不同视角；本页的判定规则是综合后的工作标准。</p>
  </section>;
}
